//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb.ServiceReferenceTarifas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pichincha.com.co/tarifas", ConfigurationName="ServiceReferenceTarifas.SincronizarTarifasSFC")]
    public interface SincronizarTarifasSFC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pichincha.com.co/tarifas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBody))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestBody))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LoggingData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SystemException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaSincronizarTarifasSFC))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sincronizarTarifasSFC))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Header))]
        ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCResponse sincronizarTarifasSFC(ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pichincha.com.co/tarifas", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCResponse> sincronizarTarifasSFCAsync(ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
    public partial class RequestHeaderOut : Header {
        
        private SecurityCredential securityCredentialField;
        
        private Destination destinationField;
        
        private string[] classificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SecurityCredential securityCredential {
            get {
                return this.securityCredentialField;
            }
            set {
                this.securityCredentialField = value;
                this.RaisePropertyChanged("securityCredential");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", IsNullable=false)]
        public string[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class SecurityCredential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private object userTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("userToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class ResponseBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object responseField;
        
        private ExceptionList[] exceptionListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exceptionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ExceptionList[] exceptionList {
            get {
                return this.exceptionListField;
            }
            set {
                this.exceptionListField = value;
                this.RaisePropertyChanged("exceptionList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class ExceptionList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BaseException exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BaseException exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("exception");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class BaseException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class RequestBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class LoggingData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceSystemIdField;
        
        private string destinationSystemIdField;
        
        public LoggingData() {
            this.destinationSystemIdField = "ESB";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sourceSystemId {
            get {
                return this.sourceSystemIdField;
            }
            set {
                this.sourceSystemIdField = value;
                this.RaisePropertyChanged("sourceSystemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string destinationSystemId {
            get {
                return this.destinationSystemIdField;
            }
            set {
                this.destinationSystemIdField = value;
                this.RaisePropertyChanged("destinationSystemId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class SystemException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlQualifiedName faultcodeField;
        
        private string faultstringField;
        
        private string faultactorField;
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.Xml.XmlQualifiedName faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
                this.RaisePropertyChanged("faultstring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=2)]
        public string faultactor {
            get {
                return this.faultactorField;
            }
            set {
                this.faultactorField = value;
                this.RaisePropertyChanged("faultactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pichincha.com.co/tarifas")]
    public partial class respuestaSincronizarTarifasSFC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Respuesta respuestaField;
        
        private Tarifa tarifaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Tarifa tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pichincha.com.co/general")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pichincha.com.co/general")]
    public partial class Tarifa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoEntidadField;
        
        private string entidadCodField;
        
        private string fechaReporteField;
        
        private string aperturaDigitalField;
        
        private string tasaField;
        
        private string tipoEntidadAseguradoraField;
        
        private string entidadCodAseguradoraField;
        
        private string observacionesField;
        
        private string nombreComercialField;
        
        private string numClientesUnicosField;
        
        private string cuotaManejoField;
        
        private string grupoPoblacionalField;
        
        private string obsCuotaManejoField;
        
        private string operacionServicioField;
        
        private string canalField;
        
        private string costoFijoField;
        
        private string costoPropOperServField;
        
        private string codigoCreditoField;
        
        private string caracteristicaCreditoField;
        
        private string costoField;
        
        private string franquiciaField;
        
        private string cuotaManejoMaximaField;
        
        private string cupoField;
        
        private string servicioGratuito1Field;
        
        private string servicioGratuito2Field;
        
        private string servicioGratuito3Field;
        
        private string costoFijoMaximoField;
        
        private string costoPropMaxOperServField;
        
        private string tasaMaximaField;
        
        private string tipoProductoField;
        
        private string ingresosField;
        
        private string cuentaAhorros1Field;
        
        private string cuentaAhorros2Field;
        
        private string cuentaAhorros3Field;
        
        private string tarjetaDebito1Field;
        
        private string tarjetaDebito2Field;
        
        private string tarjetaDebito3Field;
        
        private string numOperServCuotaManejoField;
        
        private string codigoRegistroCabSFCField;
        
        private string codigoRegistroUcSFCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipoEntidad {
            get {
                return this.tipoEntidadField;
            }
            set {
                this.tipoEntidadField = value;
                this.RaisePropertyChanged("tipoEntidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string entidadCod {
            get {
                return this.entidadCodField;
            }
            set {
                this.entidadCodField = value;
                this.RaisePropertyChanged("entidadCod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fechaReporte {
            get {
                return this.fechaReporteField;
            }
            set {
                this.fechaReporteField = value;
                this.RaisePropertyChanged("fechaReporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string aperturaDigital {
            get {
                return this.aperturaDigitalField;
            }
            set {
                this.aperturaDigitalField = value;
                this.RaisePropertyChanged("aperturaDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tasa {
            get {
                return this.tasaField;
            }
            set {
                this.tasaField = value;
                this.RaisePropertyChanged("tasa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tipoEntidadAseguradora {
            get {
                return this.tipoEntidadAseguradoraField;
            }
            set {
                this.tipoEntidadAseguradoraField = value;
                this.RaisePropertyChanged("tipoEntidadAseguradora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string entidadCodAseguradora {
            get {
                return this.entidadCodAseguradoraField;
            }
            set {
                this.entidadCodAseguradoraField = value;
                this.RaisePropertyChanged("entidadCodAseguradora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
                this.RaisePropertyChanged("nombreComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string numClientesUnicos {
            get {
                return this.numClientesUnicosField;
            }
            set {
                this.numClientesUnicosField = value;
                this.RaisePropertyChanged("numClientesUnicos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string cuotaManejo {
            get {
                return this.cuotaManejoField;
            }
            set {
                this.cuotaManejoField = value;
                this.RaisePropertyChanged("cuotaManejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string grupoPoblacional {
            get {
                return this.grupoPoblacionalField;
            }
            set {
                this.grupoPoblacionalField = value;
                this.RaisePropertyChanged("grupoPoblacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string obsCuotaManejo {
            get {
                return this.obsCuotaManejoField;
            }
            set {
                this.obsCuotaManejoField = value;
                this.RaisePropertyChanged("obsCuotaManejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string operacionServicio {
            get {
                return this.operacionServicioField;
            }
            set {
                this.operacionServicioField = value;
                this.RaisePropertyChanged("operacionServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string costoFijo {
            get {
                return this.costoFijoField;
            }
            set {
                this.costoFijoField = value;
                this.RaisePropertyChanged("costoFijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string costoPropOperServ {
            get {
                return this.costoPropOperServField;
            }
            set {
                this.costoPropOperServField = value;
                this.RaisePropertyChanged("costoPropOperServ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string codigoCredito {
            get {
                return this.codigoCreditoField;
            }
            set {
                this.codigoCreditoField = value;
                this.RaisePropertyChanged("codigoCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string caracteristicaCredito {
            get {
                return this.caracteristicaCreditoField;
            }
            set {
                this.caracteristicaCreditoField = value;
                this.RaisePropertyChanged("caracteristicaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string franquicia {
            get {
                return this.franquiciaField;
            }
            set {
                this.franquiciaField = value;
                this.RaisePropertyChanged("franquicia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string cuotaManejoMaxima {
            get {
                return this.cuotaManejoMaximaField;
            }
            set {
                this.cuotaManejoMaximaField = value;
                this.RaisePropertyChanged("cuotaManejoMaxima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string cupo {
            get {
                return this.cupoField;
            }
            set {
                this.cupoField = value;
                this.RaisePropertyChanged("cupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string servicioGratuito1 {
            get {
                return this.servicioGratuito1Field;
            }
            set {
                this.servicioGratuito1Field = value;
                this.RaisePropertyChanged("servicioGratuito1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string servicioGratuito2 {
            get {
                return this.servicioGratuito2Field;
            }
            set {
                this.servicioGratuito2Field = value;
                this.RaisePropertyChanged("servicioGratuito2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string servicioGratuito3 {
            get {
                return this.servicioGratuito3Field;
            }
            set {
                this.servicioGratuito3Field = value;
                this.RaisePropertyChanged("servicioGratuito3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string costoFijoMaximo {
            get {
                return this.costoFijoMaximoField;
            }
            set {
                this.costoFijoMaximoField = value;
                this.RaisePropertyChanged("costoFijoMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string costoPropMaxOperServ {
            get {
                return this.costoPropMaxOperServField;
            }
            set {
                this.costoPropMaxOperServField = value;
                this.RaisePropertyChanged("costoPropMaxOperServ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string tasaMaxima {
            get {
                return this.tasaMaximaField;
            }
            set {
                this.tasaMaximaField = value;
                this.RaisePropertyChanged("tasaMaxima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ingresos {
            get {
                return this.ingresosField;
            }
            set {
                this.ingresosField = value;
                this.RaisePropertyChanged("ingresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string cuentaAhorros1 {
            get {
                return this.cuentaAhorros1Field;
            }
            set {
                this.cuentaAhorros1Field = value;
                this.RaisePropertyChanged("cuentaAhorros1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string cuentaAhorros2 {
            get {
                return this.cuentaAhorros2Field;
            }
            set {
                this.cuentaAhorros2Field = value;
                this.RaisePropertyChanged("cuentaAhorros2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string cuentaAhorros3 {
            get {
                return this.cuentaAhorros3Field;
            }
            set {
                this.cuentaAhorros3Field = value;
                this.RaisePropertyChanged("cuentaAhorros3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string tarjetaDebito1 {
            get {
                return this.tarjetaDebito1Field;
            }
            set {
                this.tarjetaDebito1Field = value;
                this.RaisePropertyChanged("tarjetaDebito1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string tarjetaDebito2 {
            get {
                return this.tarjetaDebito2Field;
            }
            set {
                this.tarjetaDebito2Field = value;
                this.RaisePropertyChanged("tarjetaDebito2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string tarjetaDebito3 {
            get {
                return this.tarjetaDebito3Field;
            }
            set {
                this.tarjetaDebito3Field = value;
                this.RaisePropertyChanged("tarjetaDebito3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string numOperServCuotaManejo {
            get {
                return this.numOperServCuotaManejoField;
            }
            set {
                this.numOperServCuotaManejoField = value;
                this.RaisePropertyChanged("numOperServCuotaManejo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string codigoRegistroCabSFC {
            get {
                return this.codigoRegistroCabSFCField;
            }
            set {
                this.codigoRegistroCabSFCField = value;
                this.RaisePropertyChanged("codigoRegistroCabSFC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string codigoRegistroUcSFC {
            get {
                return this.codigoRegistroUcSFCField;
            }
            set {
                this.codigoRegistroUcSFCField = value;
                this.RaisePropertyChanged("codigoRegistroUcSFC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pichincha.com.co/tarifas")]
    public partial class sincronizarTarifasSFC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InformacionCanal canalField;
        
        private string codigoProductoField;
        
        private Tarifa tarifaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InformacionCanal canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Tarifa tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pichincha.com.co/general")]
    public partial class InformacionCanal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string canalField;
        
        private string segmentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
                this.RaisePropertyChanged("segmento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class EndPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string correlationIdField;
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("correlationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class RouteData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndPoint callBackToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public EndPoint CallBackTo {
            get {
                return this.callBackToField;
            }
            set {
                this.callBackToField = value;
                this.RaisePropertyChanged("CallBackTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class Destination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string namespaceField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=1)]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
                this.RaisePropertyChanged("namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseStatusStatusCode statusCodeField;
        
        public ResponseStatus() {
            this.statusCodeField = ResponseStatusStatusCode.SUCCESS;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatusStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pragma.co/ents/common/BaseExtensions/V1.0")]
    public enum ResponseStatusStatusCode {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        PROVIDEREXCEPTION,
        
        /// <remarks/>
        TECHNICALEXCEPTION,
        
        /// <remarks/>
        BUSINESSEXCEPTION,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestHeaderIn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseHeaderOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestHeaderOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseHeaderIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
    public abstract partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string messageIdField;
        
        private System.DateTime invokerDateTimeField;
        
        private bool invokerDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime invokerDateTime {
            get {
                return this.invokerDateTimeField;
            }
            set {
                this.invokerDateTimeField = value;
                this.RaisePropertyChanged("invokerDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invokerDateTimeSpecified {
            get {
                return this.invokerDateTimeFieldSpecified;
            }
            set {
                this.invokerDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("invokerDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
    public partial class RequestHeaderIn : Header {
        
        private SecurityCredential securityCredentialField;
        
        private Destination destinationField;
        
        private string[] classificationField;
        
        private Property[] messageContextField;
        
        private RouteData[] routingStackField;
        
        private string componentNameLoggingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SecurityCredential securityCredential {
            get {
                return this.securityCredentialField;
            }
            set {
                this.securityCredentialField = value;
                this.RaisePropertyChanged("securityCredential");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", IsNullable=false)]
        public string[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
                this.RaisePropertyChanged("messageContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("routeTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RouteData[] routingStack {
            get {
                return this.routingStackField;
            }
            set {
                this.routingStackField = value;
                this.RaisePropertyChanged("routingStack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string componentNameLogging {
            get {
                return this.componentNameLoggingField;
            }
            set {
                this.componentNameLoggingField = value;
                this.RaisePropertyChanged("componentNameLogging");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
    public partial class ResponseHeaderOut : Header {
        
        private ResponseStatus responseStatusField;
        
        private Destination destinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
    public partial class ResponseHeaderIn : Header {
        
        private ResponseStatus responseStatusField;
        
        private Destination destinationField;
        
        private Property[] messageContextField;
        
        private RouteData[] routingStackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
                this.RaisePropertyChanged("messageContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("routeTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RouteData[] routingStack {
            get {
                return this.routingStackField;
            }
            set {
                this.routingStackField = value;
                this.RaisePropertyChanged("routingStack");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sincronizarTarifasSFC", WrapperNamespace="http://www.pichincha.com.co/tarifas", IsWrapped=true)]
    public partial class sincronizarTarifasSFCRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
        public ProyectoWeb.ServiceReferenceTarifas.RequestHeaderOut requestHeaderOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pichincha.com.co/tarifas", Order=0)]
        public ProyectoWeb.ServiceReferenceTarifas.InformacionCanal canal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pichincha.com.co/tarifas", Order=1)]
        public string codigoProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pichincha.com.co/tarifas", Order=2)]
        public ProyectoWeb.ServiceReferenceTarifas.Tarifa tarifa;
        
        public sincronizarTarifasSFCRequest() {
        }
        
        public sincronizarTarifasSFCRequest(ProyectoWeb.ServiceReferenceTarifas.RequestHeaderOut requestHeaderOut, ProyectoWeb.ServiceReferenceTarifas.InformacionCanal canal, string codigoProducto, ProyectoWeb.ServiceReferenceTarifas.Tarifa tarifa) {
            this.requestHeaderOut = requestHeaderOut;
            this.canal = canal;
            this.codigoProducto = codigoProducto;
            this.tarifa = tarifa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="respuestaSincronizarTarifasSFC", WrapperNamespace="http://www.pichincha.com.co/tarifas", IsWrapped=true)]
    public partial class sincronizarTarifasSFCResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://pragma.co/ents/common/BaseMessageFormat/V1")]
        public ProyectoWeb.ServiceReferenceTarifas.ResponseHeaderOut responseHeaderOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pichincha.com.co/tarifas", Order=0)]
        public ProyectoWeb.ServiceReferenceTarifas.Respuesta respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pichincha.com.co/tarifas", Order=1)]
        public ProyectoWeb.ServiceReferenceTarifas.Tarifa tarifa;
        
        public sincronizarTarifasSFCResponse() {
        }
        
        public sincronizarTarifasSFCResponse(ProyectoWeb.ServiceReferenceTarifas.ResponseHeaderOut responseHeaderOut, ProyectoWeb.ServiceReferenceTarifas.Respuesta respuesta, ProyectoWeb.ServiceReferenceTarifas.Tarifa tarifa) {
            this.responseHeaderOut = responseHeaderOut;
            this.respuesta = respuesta;
            this.tarifa = tarifa;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SincronizarTarifasSFCChannel : ProyectoWeb.ServiceReferenceTarifas.SincronizarTarifasSFC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SincronizarTarifasSFCClient : System.ServiceModel.ClientBase<ProyectoWeb.ServiceReferenceTarifas.SincronizarTarifasSFC>, ProyectoWeb.ServiceReferenceTarifas.SincronizarTarifasSFC {
        
        public SincronizarTarifasSFCClient() {
        }
        
        public SincronizarTarifasSFCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SincronizarTarifasSFCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizarTarifasSFCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizarTarifasSFCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCResponse ProyectoWeb.ServiceReferenceTarifas.SincronizarTarifasSFC.sincronizarTarifasSFC(ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest request) {
            return base.Channel.sincronizarTarifasSFC(request);
        }
        
        public ProyectoWeb.ServiceReferenceTarifas.ResponseHeaderOut sincronizarTarifasSFC(ProyectoWeb.ServiceReferenceTarifas.RequestHeaderOut requestHeaderOut, ProyectoWeb.ServiceReferenceTarifas.InformacionCanal canal, string codigoProducto, ref ProyectoWeb.ServiceReferenceTarifas.Tarifa tarifa, out ProyectoWeb.ServiceReferenceTarifas.Respuesta respuesta) {
            ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest inValue = new ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest();
            inValue.requestHeaderOut = requestHeaderOut;
            inValue.canal = canal;
            inValue.codigoProducto = codigoProducto;
            inValue.tarifa = tarifa;
            ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCResponse retVal = ((ProyectoWeb.ServiceReferenceTarifas.SincronizarTarifasSFC)(this)).sincronizarTarifasSFC(inValue);
            respuesta = retVal.respuesta;
            tarifa = retVal.tarifa;
            return retVal.responseHeaderOut;
        }
        
        public System.Threading.Tasks.Task<ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCResponse> sincronizarTarifasSFCAsync(ProyectoWeb.ServiceReferenceTarifas.sincronizarTarifasSFCRequest request) {
            return base.Channel.sincronizarTarifasSFCAsync(request);
        }
    }
}
